server:
  port: 8080
mysql:
  host: localhost
  port: 3306
  user: root
  password: root123
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600 # 1 min
logger:
  log_level: debug
  file_name: "./log/dev-output.xxx.log"
  max_size: 500 # megabytes
  max_backups: 3
  max_age: 28 # days
  compress: true
redis:
  host: localhost
  port: 6381
  password:
  db: 0
  pool_size: 10